package com.example.example.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "BackupPhotoInfo".
 */
public class BackupPhotoInfo {

    private Long id;
    private String fileName;
    private String filePath;
    private Long fileSize;
    private String md5;
    private Boolean state;
    private Integer cancelState;

    public BackupPhotoInfo() {
    }

    public BackupPhotoInfo(Long id) {
        this.id = id;
    }

    public BackupPhotoInfo(Long id, String fileName, String filePath, Long fileSize, String md5, Boolean state, Integer cancelState) {
        this.id = id;
        this.fileName = fileName;
        this.filePath = filePath;
        this.fileSize = fileSize;
        this.md5 = md5;
        this.state = state;
        this.cancelState = cancelState;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public Boolean getState() {
        return state;
    }

    public void setState(Boolean state) {
        this.state = state;
    }

    public Integer getCancelState() {
        return cancelState;
    }

    public void setCancelState(Integer cancelState) {
        this.cancelState = cancelState;
    }

}
