package com.example.example.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "CloudDevice".
 */
public class CloudDevice {

    private String did;
    private String user_id;
    private String address;
    private Integer online;
    private String certificate;
    private String key;
    private String token;
    private Boolean current_device;
    private String dname;
    private Integer isRelay;
    private Integer isRemoteCan;

    public CloudDevice() {
    }

    public CloudDevice(String did) {
        this.did = did;
    }

    public CloudDevice(String did, String user_id, String address, Integer online, String certificate, String key, String token, Boolean current_device, String dname, Integer isRelay, Integer isRemoteCan) {
        this.did = did;
        this.user_id = user_id;
        this.address = address;
        this.online = online;
        this.certificate = certificate;
        this.key = key;
        this.token = token;
        this.current_device = current_device;
        this.dname = dname;
        this.isRelay = isRelay;
        this.isRemoteCan = isRemoteCan;
    }

    public String getDid() {
        return did;
    }

    public void setDid(String did) {
        this.did = did;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Integer getOnline() {
        return online;
    }

    public void setOnline(Integer online) {
        this.online = online;
    }

    public String getCertificate() {
        return certificate;
    }

    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public Boolean getCurrent_device() {
        return current_device;
    }

    public void setCurrent_device(Boolean current_device) {
        this.current_device = current_device;
    }

    public String getDname() {
        return dname;
    }

    public void setDname(String dname) {
        this.dname = dname;
    }

    public Integer getIsRelay() {
        return isRelay;
    }

    public void setIsRelay(Integer isRelay) {
        this.isRelay = isRelay;
    }

    public Integer getIsRemoteCan() {
        return isRemoteCan;
    }

    public void setIsRemoteCan(Integer isRemoteCan) {
        this.isRemoteCan = isRemoteCan;
    }

}
