package com.example.example.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "DownloadInfo".
 */
public class DownloadInfo {

    private Long id;
    private String userName;
    private String did;
    private String url;
    private String fileType;
    private String type;
    private String localPath;
    private Long fileSize;
    private Long state;
    private Long complete;
    private String fileName;
    private String createTime;
    private Integer errorMessage;

    public DownloadInfo() {
    }

    public DownloadInfo(Long id) {
        this.id = id;
    }

    public DownloadInfo(Long id, String userName, String did, String url, String fileType, String type, String localPath, Long fileSize, Long state, Long complete, String fileName, String createTime, Integer errorMessage) {
        this.id = id;
        this.userName = userName;
        this.did = did;
        this.url = url;
        this.fileType = fileType;
        this.type = type;
        this.localPath = localPath;
        this.fileSize = fileSize;
        this.state = state;
        this.complete = complete;
        this.fileName = fileName;
        this.createTime = createTime;
        this.errorMessage = errorMessage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getDid() {
        return did;
    }

    public void setDid(String did) {
        this.did = did;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getFileType() {
        return fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getLocalPath() {
        return localPath;
    }

    public void setLocalPath(String localPath) {
        this.localPath = localPath;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public Long getState() {
        return state;
    }

    public void setState(Long state) {
        this.state = state;
    }

    public Long getComplete() {
        return complete;
    }

    public void setComplete(Long complete) {
        this.complete = complete;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public Integer getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(Integer errorMessage) {
        this.errorMessage = errorMessage;
    }

}
