package com.example.example.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "LocalUser".
 */
public class LocalUser {

    private String user_id;
    private String user_name;
    private String user_password;
    private String cloud_name;
    private Integer login_flg;
    private Integer cloud_type;
    private String token;
    private String refresh_token;
    private Boolean current_account;
    private String did;

    public LocalUser() {
    }

    public LocalUser(String user_id) {
        this.user_id = user_id;
    }

    public LocalUser(String user_id, String user_name, String user_password, String cloud_name, Integer login_flg, Integer cloud_type, String token, String refresh_token, Boolean current_account, String did) {
        this.user_id = user_id;
        this.user_name = user_name;
        this.user_password = user_password;
        this.cloud_name = cloud_name;
        this.login_flg = login_flg;
        this.cloud_type = cloud_type;
        this.token = token;
        this.refresh_token = refresh_token;
        this.current_account = current_account;
        this.did = did;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getUser_password() {
        return user_password;
    }

    public void setUser_password(String user_password) {
        this.user_password = user_password;
    }

    public String getCloud_name() {
        return cloud_name;
    }

    public void setCloud_name(String cloud_name) {
        this.cloud_name = cloud_name;
    }

    public Integer getLogin_flg() {
        return login_flg;
    }

    public void setLogin_flg(Integer login_flg) {
        this.login_flg = login_flg;
    }

    public Integer getCloud_type() {
        return cloud_type;
    }

    public void setCloud_type(Integer cloud_type) {
        this.cloud_type = cloud_type;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getRefresh_token() {
        return refresh_token;
    }

    public void setRefresh_token(String refresh_token) {
        this.refresh_token = refresh_token;
    }

    public Boolean getCurrent_account() {
        return current_account;
    }

    public void setCurrent_account(Boolean current_account) {
        this.current_account = current_account;
    }

    public String getDid() {
        return did;
    }

    public void setDid(String did) {
        this.did = did;
    }

}
