package com.example.example.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "RecentInfo".
 */
public class RecentInfo {

    private String fileType;
    private String user;
    private String did;
    private String filePath;
    private Long time;
    private Boolean isLocal;
    private String fileName;
    private String id;
    private String createTime;
    private String fileSize;
    private String musicAlbum;
    private String musicSinger;
    private String mediaTime;
    private Integer collectFlg;
    private Integer shareFlg;

    public RecentInfo() {
    }

    public RecentInfo(Long time) {
        this.time = time;
    }

    public RecentInfo(String fileType, String user, String did, String filePath, Long time, Boolean isLocal, String fileName, String id, String createTime, String fileSize, String musicAlbum, String musicSinger, String mediaTime, Integer collectFlg, Integer shareFlg) {
        this.fileType = fileType;
        this.user = user;
        this.did = did;
        this.filePath = filePath;
        this.time = time;
        this.isLocal = isLocal;
        this.fileName = fileName;
        this.id = id;
        this.createTime = createTime;
        this.fileSize = fileSize;
        this.musicAlbum = musicAlbum;
        this.musicSinger = musicSinger;
        this.mediaTime = mediaTime;
        this.collectFlg = collectFlg;
        this.shareFlg = shareFlg;
    }

    public String getFileType() {
        return fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getDid() {
        return did;
    }

    public void setDid(String did) {
        this.did = did;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Boolean getIsLocal() {
        return isLocal;
    }

    public void setIsLocal(Boolean isLocal) {
        this.isLocal = isLocal;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getFileSize() {
        return fileSize;
    }

    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    public String getMusicAlbum() {
        return musicAlbum;
    }

    public void setMusicAlbum(String musicAlbum) {
        this.musicAlbum = musicAlbum;
    }

    public String getMusicSinger() {
        return musicSinger;
    }

    public void setMusicSinger(String musicSinger) {
        this.musicSinger = musicSinger;
    }

    public String getMediaTime() {
        return mediaTime;
    }

    public void setMediaTime(String mediaTime) {
        this.mediaTime = mediaTime;
    }

    public Integer getCollectFlg() {
        return collectFlg;
    }

    public void setCollectFlg(Integer collectFlg) {
        this.collectFlg = collectFlg;
    }

    public Integer getShareFlg() {
        return shareFlg;
    }

    public void setShareFlg(Integer shareFlg) {
        this.shareFlg = shareFlg;
    }

}
